config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  get 'landing/index'
  get '/dashboard'=>'landing#dashboard'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :questions
  devise_for :users
  get 'home/index'
  get '/ide'=>'landing#ide'
  get '/users'=>"home#index"
  get '/solve'=>'questions#show'
  post '/evaluate'=>'questions#evaluate'
  post '/ideevaluate'=>'landing#evaluate'
  get '/questions'=>'questions#index'
  get '/posts'=>'posts#index'

  root to: "landing#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user! , only: [:edit,:create, :update, :destroy]
  # GET /comments
  # GET /comments.json
  def index
    # @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
   @comment = Comment.new(post_id: params[:post_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
      @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to '/posts/', notice: 'Comment was successfully created.' }
        format.js{  }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render  '/posts/'}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_field :references %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comments').prepend("<%= escape_javascript (render 'posts/comment', comment: @comment) %>");
$('#comment').val("");

app/views/comments/edit.html.erb
<%if can? :update,@comment%>
<h1>Editing Comment</h1>

<%= render 'form' %>
<%= link_to 'Show', @comment %> |
<%= link_to 'Back', posts_path %>
<%else%>
<%= render file: 'public/404', status: 404, formats: [:html] %>
<%end%>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>References</th>
      <th>References</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.references %></td>
        <td><%= comment.references %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.email %>
</p>
<%if can? :update,@comment%>
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%end%>
<%= link_to 'Back', post_path(@comment.post)  %>